POST http://localhost:5000/api/auth/getuser
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjk1OTE0OTI0ZmY2YmNkOTRiOTBhZjFiIn0sImlhdCI6MTc2NzQ2OTA2OX0.pY790c2nigKQ8jkjvyGEP7A0i6-eBfGhDFYUKW-Kbtw